version: 2.1
orbs:
  auto_test: nowsecure/ci-auto-orb@1.0.7
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: /tmp/myworkspace
      - checkout
      - run: cp anydo39.apk /tmp/myworkspace/test.apk
      - auto_test/mobile_security_test:
          auto_file: /tmp/myworkspace/test.apk
          auto_wait: "45"
          auto_score: "30"
          auto_show_status_messages: "true"
          auto_group: "be50cb1e-f934-11e6-a267-639282966b4b"
          auto_token: $AUTO_TOKEN
